version: "3"

services:
  database:
    build: ./database
    container_name: exitpass_database
    restart: always
    volumes:
      - ./database:/exitpass/database/
  backend:
    build: ./backend
    container_name: exitpass_backend
    restart: always
    volumes:
      - ./backend:/exitpass/backend/
    ports:
      - '7082:7082'
    depends_on:
      - database
    links:
      - database
    environment:
      WAIT_HOSTS: database:3306
  frontend:
    build: ./frontend
    container_name: exitpass_frontend
    volumes:
      - ./frontend:/exitpass/frontend/
    # ports:
    #   - '8080:8080'
  nginx:
    build: ./nginx
    container_name: exitpass_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/rdapps.conf:/etc/nginx/conf.d/rdapps.conf
      - ./frontend:/exitpass/frontend/
    ports:
      - '6999:80'
    depends_on:
      - frontend
      - backend
      - database
